### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jph00** [HJ-harry/MCG_diffusion#2]
Many thanks for sharing this code, and for your interesting paper.

Could you please add a LICENSE file to the repo, so that the license for using this repo's code is clear? Some files in here explicitly say they're under Apache 2, but some don't.

Unfortunately without a license, the code here can't be legally used for any purpose AFAIK.

**Comment by hyungjin-chung** [comment]
Thanks for the ping! License is now included.
