### ISSUE TITLE
How does it work for inverse problems with unknown degradations

### ISSUE THREAD

**Issue by Zwette** [HJ-harry/MCG_diffusion#5]
Thanks for your excellent work. I am wondering how the proposed method works when the inverse problem contains unknown degradation, which means that the matrix H and A cannot be defined such as real haze removal and blind super resolution.

**Comment by hyungjin-chung** [comment]
The scope of this work is restricted to **Non-blind linear** operators. For blind inverse problem solving with diffusion, you may want to check out [this paper](https://arxiv.org/abs/2211.10656)
