### ISSUE TITLE
Validation dataset

### ISSUE THREAD

**Issue by sojinleeme** [HJ-harry/MCG_diffusion#6]
Thanks for your interesting work!
I want to reproduce about inpainting and colorization (Table 1, 2).
In each task, can you know me the list of validation set images (1K for FFHQ and ImageNet, 0.3K for LSUN)?

**Comment by hyungjin-chung** [comment]
Thanks for your interest and the kind words!

FFHQ: 0-1000 out of all the images
ImageNet: the first 1000 images out of the validation set (note that we drop images that are below the resolution 256x256, so it is not exactly the first 1000)
LSUN: all 300 images in the validation set

Hope this clarifies your question

**Comment by sojinleeme** [comment]
Thank you!!
