### ISSUE TITLE
About freq usage in predictor and corrector algorithm (controllable_generation.py:192)

### ISSUE THREAD

**Issue by wenjing11** [HJ-harry/MCG_diffusion#7]
Thanks for your amazing work!

In controllable_generation.py line 192, variable "freq" is used to select different corrector algorithm, but I do not find any description in MCG paper or Song's paper. 
Besides, I do not find trainning code in repo, which is important for me to reproduce the result.

Any help will be appreciated!

**Comment by hyungjin-chung** [comment]
You can use the training script directly from [this repo](https://github.com/yang-song/score_sde_pytorch) and use the trained model for use in the codes provided in our repository. ```freq``` is used to control the frequency of corrector steps to be applied per predictor step, but it is always set to 1. You can simply ignore it.
