### ISSUE TITLE
Where can i find the original pre-trained model in FFHQ?

### ISSUE THREAD

**Issue by kevin-on** [HJ-harry/MCG_diffusion#8]
Hello, I hope this message finds you well.

Where can I find the original pre-trained model trained with 256x256 FFHQ? (_ffhq_10m.pt_ )
I cannot find the model in the guided-diffusion repo (https://github.com/openai/guided-diffusion).

Thank you very much for your help!

**Comment by hyungjin-chung** [comment]
Please see [this script](https://github.com/HJ-harry/MCG_diffusion/blob/main/install.sh)
